version: "3"

#volumes:
#  maven-repo:
#    /home/oper/notes/new_work/cust_trial/maven_repo/

services:
    results-control-api-gateway-svc:
        restart: on-failure
        container_name: results-control-api-gateway_docker
        build:
            context: results-control-api-gateway
            dockerfile: ../Dockerfile

        image: results-control-api-gateway_docker:latest
        networks:
            - network
        ports:
            - "8080:8080"
        depends_on:
            - rabbitMQ
            - personal-information-svc
            - academic-performance-svc
            - period-planning-svc
            - schedule-calendar-svc

    personal-information-svc:
        restart: on-failure
        container_name: personal-information_docker
        build:
            context: personal-information
            dockerfile: ../Dockerfile

        image: personal-information_docker:latest
        networks:
            - network
        ports:
            - "8083:8080"
        depends_on:
            - db_pi
        links:
            - db_pi

    academic-performance-svc:
        restart: on-failure
        container_name: academic-performance_docker
        build:
            context: academic-performance
            dockerfile: ../Dockerfile

        image: academic-performance_docker:latest
        networks:
            - network
        ports:
            - "8084:8080"
        depends_on:
            - db_ap
#            - rabbitMQ
        links:
            - db_ap
#            - rabbitMQ

    period-planning-svc:
        restart: on-failure
        container_name: period-planning_docker
        build:
            context: period-planning
            dockerfile: ../Dockerfile

        image: period-planning_docker:latest
        networks:
            - network
        ports:
            - "8085:8080"
        depends_on:
            - db_pp
        links:
            - db_pp

    schedule-calendar-svc:
        restart: on-failure
        container_name: schedule-calendar_docker
        build:
            context: schedule-calendar
            dockerfile: ../Dockerfile

        image: schedule-calendar_docker:latest
        networks:
            - network
        ports:
            - "8086:8080"
        depends_on:
            - db_sc
#            - rabbitMQ
        links:
            - db_sc
#            - rabbitMQ


    rabbitMQ:
        restart: on-failure
        image: rabbitmq:latest
        container_name: rabbitmq
        ports:
         - "5672:5672"
         - "15672:15672"

        networks:
           - network

#create DB for all services: academic-performance (ap), period-planning(pp), schedule-calendar(sc), personal-information(pi)
    db_ap:
        restart: on-failure
        image: "postgres"
        container_name: db_ap
        env_file:
           - database.env # configure postgres
        volumes:
          - ./pg_db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - network


    db_pp:
        restart: on-failure
        image: "postgres"
        container_name: db_pp
        env_file:
           - database.env # configure postgres
        volumes:
          - ./pg_db/init.sql:/docker-entrypoint-initdb.d/init.sql

        networks:
            - network


    db_sc:
        restart: on-failure
        image: "postgres"
        container_name: db_sc
        env_file:
           - database.env # configure postgres
        volumes:
          - ./pg_db/init.sql:/docker-entrypoint-initdb.d/init.sql

        networks:
            - network

    db_pi:
        restart: on-failure
        image: "postgres"
        container_name: db_pi
        env_file:
           - database.env # configure postgres
        volumes:
          - ./pg_db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - network


networks:
  network: {}
